# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-28 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=10, max_digits=20)),
                ('lng', models.DecimalField(decimal_places=10, max_digits=20)),
                ('place_id', models.TextField()),
                ('name', models.TextField()),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('zip_code', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone_number', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lng', models.DecimalField(decimal_places=10, max_digits=20)),
                ('lat', models.DecimalField(decimal_places=10, max_digits=20)),
                ('gender', models.CharField(choices=[(b'cis-woman', b'cis-woman'), (b'cis-man', b'cis-man'), (b'non-binary', b'non-binary'), (b'trans-woman', b'trans-woman'), (b'trans-man', b'trans-man'), (b'other', b'other'), (b'do not wish to disclose', b'do not wish to disclose')], default=b'do not wish to disclose', max_length=200)),
                ('assailant', models.CharField(choices=[(b'romantic partner', b'romantic partner'), (b'friend', b'friend'), (b'teacher', b'teacher'), (b'boss', b'boss'), (b'family member', b'family member'), (b'stranger', b'stranger'), (b'police', b'police'), (b'do not wish to disclose', b'do not wish to disclose')], default=b'do not wish to disclose', max_length=200)),
                ('type_of_abuse', models.CharField(choices=[(b'rape', b'rape'), (b'controlling behaviour', b'controlling behaviour'), (b'partner assault', b'partner assault'), (b'stalking', b'stalking'), (b'indecent exposure', b'indecent exposure'), (b'pornography', b'pornography'), (b'cyber bullying', b'cyber bullying'), (b'genital mutilation', b'genital mutilation'), (b'threats of physical violence', b'threats of physical violence'), (b'incest', b'incest')], default=b'do not wish to disclose', max_length=200)),
                ('location', models.CharField(choices=[(b'in a public space', b'in a public space'), (b'on a college campus', b'on a college campus'), (b'at or near your home', b'at or near your home'), (b"at or near a relative's home", b"at or near a relative's home")], default=b'do not wish to disclose', max_length=200)),
                ('report', models.CharField(choices=[(b'yes', b'yes'), (b'no', b'no'), (b'do not wish to disclose', b'do not wish to disclose')], default=b'do not wish to disclose', max_length=200)),
                ('story', models.TextField(blank=True, null=True)),
                ('permission', models.BooleanField(default=False)),
                ('post_id', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
