# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-27 23:11
from __future__ import unicode_literals

from django.db import migrations

def seed_resources(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Resource = apps.get_model("hello", "Resources")
    Resource.objects.create(
    	latitude=37.762387, 
    	longitude=-122.422728,
    	name="SF Women Against Rape",
    	address="3543 18th St #7",
    	city="San Francisco",
    	state="CA",
    	zip_code="94110",
    	phone_number="+1 415-861-2024",
    	url="sfwar.org").save()

    Resource.objects.create(
    	latitude=37.446755, 
    	longitude=-122.158164,
    	name="Center for Relationship Abuse",
    	address="555 Bryant Street #272",
    	city="Palo Alto",
    	state="CA",
    	zip_code="94301",
    	phone_number="+1 659-752-6768",
    	url="stoprelationshipabuse.org").save()

    Resource.objects.create(
    	latitude=37.762387, 
    	longitude=-122.422728,
    	name="Rape Crisis Center",
    	address="1841 Market St",
    	city="San Francisco",
    	state="CA",
    	zip_code="94110",
    	phone_number="+1 415-647-7273",
    	url="sfwar.org").save()

class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
    	migrations.RunPython(seed_resources),
    ]
