# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-27 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_text', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('longitude', models.PositiveIntegerField()),
                ('latitude', models.PositiveIntegerField()),
            ],
        ),
    ]
