# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-27 23:11
from __future__ import unicode_literals

from django.db import migrations

def seed_stories(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Stories = apps.get_model("hello", "Stories")
    Stories.objects.create(
    	latitude=37.784689,
    	longitude=-122.412260,
    	html_text="SF story here beep boop boop beep bepp boop boop").save()
    Stories.objects.create(
    	latitude=40.555296,
    	longitude=-74.159294,
    	html_text="This is a NY story beep boop boop beep boop boop boop").save()

class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_seed_resources'),
    ]

    operations = [
    	migrations.RunPython(seed_stories),
    ]
