# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-27 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_stories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=15)),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('country', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('phone_number', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='stories',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stories',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=15),
        ),
    ]
