# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-28 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20160827_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
