# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-28 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20160828_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='stories',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
    ]
